### ISSUE TITLE
IM0, IM1, IM2...

### ISSUE THREAD

**Issue by DustinWatts** [zapta/pio_tft#1]
Hi Zapta,

In main.cpp you state the following:

```
// This program uses 8 bits data path. Make sure to wire
// ILI9488 IM2=1, IM1=1, IM0=0;
```

Are you sure about this? The datasheet says: 
<img width="799" alt="Screen Shot 2021-08-20 at 17 54 45" src="https://user-images.githubusercontent.com/18088135/130260965-edbe1b97-430f-4602-907d-062fb0f1fb20.png">

`IM2=0, IM1=1, IM0=1;`

**Comment by zapta** [comment]
Yes, you are right. The comment seems to be incorrect. The schematic and
the datasheet are correct. Should be IM2=0, IM1=1, IM0=1

**Comment by zapta** [comment]
... BTW, I went to correct the comment but can't find it. Am I missing
something?

https://github.com/zapta/simple_stepper_motor_analyzer/blob/main/platformio/src/main.cpp

**Comment by zapta** [comment]
Oops, just realized that you are referring to a different github
repository.

My latest real code is here
https://github.com/zapta/simple_stepper_motor_analyzer

Please let me know ifit's hard to find things there.  The main TFT related
code is under platformio/src/display and the schematic is under 'kicad'.

**Comment by zapta** [comment]
I fixed the comment in pio_tft. It did work for me but since then I made
some changes in the actual product code at simple_stepper_motor_analyzer. I
suggest sticking to one of them since there may be differences between them
(e.g. pin assignments to simplify PCB routing).

**Comment by DustinWatts** [comment]
For me this works now! I used the IM states I posted earlier and running just fine, thanks!

**Comment by zapta** [comment]
Excellent!

If you also want to ready the screen (e.g. to capture screenshots for
documentation), I also have PIO code for that. It requires an addition
TFT_RD signal to be connected.

**Comment by zapta** [comment]
Misleading comment in main.cpp fixed.
